In [1]:
import torch
import os
os.chdir('../')
print(os.getcwd())

/home/intern_lhj/linear_evaluation


In [6]:
list(torch.load('./trained_models/our_genscl.pth.tar')['state_dict'].values())[0][0]

tensor([ 0.0738,  0.0680,  0.0067,  ..., -0.0111,  0.1380,  0.0713],
       device='cuda:0')

In [5]:
list(torch.load('./trained_models/our_supcon.pth.tar')['state_dict'].values())[0][0]

tensor([-0.0846, -0.0570, -0.0037,  ...,  0.0464, -0.0245,  0.0538],
       device='cuda:0')

In [7]:
# GenSCL
list(torch.load('./trained_models/checkpoint_last.pth.tar')['state_dict'].values())[0][0]

tensor([ 0.0738,  0.0680,  0.0067,  ..., -0.0111,  0.1380,  0.0713],
       device='cuda:0')

In [14]:
set(torch.load('./trained_models/our_supcon.pth.tar')['state_dict'].keys()) \
.difference(set(torch.load('./trained_models/our_genscl.pth.tar')['state_dict'].keys())), 
set(torch.load('./trained_models/our_genscl.pth.tar')['state_dict'].keys()) \
.difference(set(torch.load('./trained_models/our_supcon.pth.tar')['state_dict'].keys()))

{'module.queue_teacher_label'}

In [26]:
loaded_state_dict = torch.load('./trained_models/our_supcon.pth.tar')['state_dict']
print(len(loaded_state_dict))
new_state_dict = dict()
for name, params in loaded_state_dict.items():
    if name.startswith("module.encoder_q") and not name.startswith("module.encoder_q.fc"):
        name = name.replace('module.encoder_q.', '')
        new_state_dict[name] = params

print(len(new_state_dict))



647
318


In [29]:
from resnet_big import resnet50
import torchvision

model = resnet50()
model = torchvision.models.resnet50(weights = None)
model.fc = torch.nn.Module()

In [30]:
model.load_state_dict(new_state_dict, strict = True)

<All keys matched successfully>